function output = aminot(in)
%AMINOT Helper function for aminolookup

%   Copyright 2002-2004 The MathWorks, Inc.
%   $Revision: 1.7.4.2 $  $Date: 2005/06/09 21:57:17 $

a=[...
    'A	   Ala		alanine                       ';...
    'R	   Arg		arginine                      ';...
    'N	   Asn		asparagine                    ';...
    'D	   Asp		asparatic acid                ';...
    'C	   Cys		cysteine                      ';...
    'Q	   Gln		glutamine                     ';...
    'E	   Glu		glutamic acid                 ';...
    'G	   Gly		glycine                       ';...
    'H	   His		histidine                     ';...
    'I	   Ile		isoleucine                    ';...
    'L	   Leu		leucine                       ';...
    'K	   Lys		lysine                        ';...
    'M	   Met		methionine                    ';...
    'F	   Phe		phenylalanine                 ';...
    'P	   Pro		proline                       ';...
    'S	   Ser		serine                        ';...
    'T	   Thr		threonine                     ';...
    'W	   Trp		tryptophan                    ';...
    'Y	   Tyr		tyrosine                      ';...
    'V	   Val		valine                        ';...
    'B	Asp or Asn	aspartic acid or asparagine'   ;...
    'Z	Glu or Gln	glutamic acid or glutamine '   ;...
    'X	   ANY		ANY                           ';...
];

b=[...
    'P	Pro          ';...
    'E	glutamic acid';...
    'Leu	leucine    ';...
];

if strcmp(in,'table')
    output = a;
else
    output = b;
end
