ix = (data.RF == 20 | data.RF == 30);
W = mod(sum(data.trimmed_VJ,2),3);
iy = W ~= 1;
iz = data.ihmmune_collapsed(:,1) == 0;
junk = find(~iz & ix & ~iy);
junk = find(~iz & (data.RF == 10) & iy);



 %%      
 i = junk(k);
 z = data.trimmed_VJ(i,:),
 x = data.reads{i};
 w = rep.J(data.ihmmune_collapsed(i,3)).Sequence;
 y = rep.V(data.ihmmune_collapsed(i,1)).Sequence;
 fprintf('%s%s\n', char(' '*ones(1,z(1))), x); 
 fprintf('%s',y); 
 fprintf(char(' '*ones(1,z(1) + length(x) + z(2) - length(w) - length(y))));
 fprintf('%s\n', w);

 
>> 8HRWU9VD data.read_id(494,:)
                                                                     GCCTCTGGATTCACCTTTAGTGGCTATTGGATGAACTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTGGCCAACATAAAGCAAGATGGGAGTGAGAAATACTATGTGGACTCTGTGAAGGGCCGATTCACCATCTCCAGAGACAACGTCAAGAACTCACTGGATCTGCAAATTAACAGCCTGAGAGCCGAGGACACGGCTGTGTATTACTGTGCGAGAGATTTGGTCGACGTGGATACAGCTCCATACGGTATGGACGTCCTGGGGCCAAGGGACCACG
GAGGTGCAGCTGGTGGAGTCTGGGGGAGGCTTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTTAGTAGCTATTGGATGAGCTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTGGCCAACATAAAGCAAGATGGAAGTGAGAAATACTATGTGGACTCTGTGAAGGGCCGATTCACCATCTCCAGAGACAACGCCAAGAACTCACTGTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCTGTGTATTACTGTGCGAGAGA            ATTACTACTACTACTACGGTATGGACGTCTGGGGCCAAGGGACCACGGTCACCGTCTCCTCAG


                                                                                                                                    CTGGAGTGGATGGGGAGGATTGATCCTAGTGACTCTTATACCAACTACAGCCCGTCCTTCCAAGGCCACGTCACCATCTCAGCTGACAAGTCCATCAGCACTGCCTACCTGCAGTGGAGCAGCCTGAAGGCCTCGGACACAGCCATGTATTACTGTGCGAGAGTCCCGATAGGAGACTGTAATGGTAACACCTGCTTCTACTACTACTACATGGACGTCTGGGGCAAAGGGACCACG
GAAGTGCAGCTGGTGCAGTCTGGAGCAGAGGTGAAAAAGCCCGGGGAGTCTCTGAGGATCTCCTGTAAGGGTTCTGGATACAGCTTTACCAGCTACTGGATCAGCTGGGTGCGCCAGATGCCCGGGAAAGGCCTGGAGTGGATGGGGAGGATTGATCCTAGTGACTCTTATACCAACTACAGCCCGTCCTTCCAAGGCCACGTCACCATCTCAGCTGACAAGTCCATCAGCACTGCCTACCTGCAGTGGAGCAGCCTGAAGGCCTCGGACACCGCCATGTATTACTGTGCGAGA                            ATTACTACTACTACTACGGTATGGACGTCTGGGGCCAAGGGACCACGGTCACCGTCTCCTCAG

>> data.trimmed_VJ(junk(k),:)

ans =

    69    16   285


>> length(data.reads{junk(k)})

ans =

   286    
        
>> rep.V(data.ihmmune_collapsed(junk(k),1))

ans = 

    Header: 'IGHV3-7'
    Sequence: [1x296 char]    
    GAGGTGCAGCTGGTGGAGTCTGGGGGAGGCTTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTTAGTAGCTATTGGATGAGCTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTGGCCAACATAAAGCAAGATGGAAGTGAGAAATACTATGTGGACTCTGTGAAGGGCCGATTCACCATCTCCAGAGACAACGCCAAGAACTCACTGTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCTGTGTATTACTGTGCGAGAGA    

>> rep.J(data.ihmmune_collapsed(junk(k),3))

ans = 

      Header: 'IGHJ6'
    Sequence: 'ATTACTACTACTACTACGGTATGGACGTCTGGGGCCAAGGGACCACGGTCACCGTCTCCTCAG'    
               
    
    
    
 

>AAONYETE                                                                                                                           GTTGAGTGGATCGGCGGGATCATCCCTATCTTTGGTACATCAAACAACGCACAGAAGTTCCAGGGCAGAGTCACGATTAGCGCGGACGAATCGACGAGCACAGCGTACATGGAGCTGAGCCGCCTGAGATCTGAGGACACGGCCGTCTATTACTGTGCGAGGGCGGAGTGTACTGGTGGTGTTTGTTATTCTCAGTACTACTGCGGTATGGACGTCTGGGGCCAAGGGACCACG
CAGGTCCAGCTGGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGTCCTCGGTGAAGGTCTCCTGCAAGGCTTCTGGAGGCACCTTCAGCAGCTATGCTATCAGCTGGGTGCGACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGAGGGATCATCCCTATCTTTGGTACAGCAAACTACGCACAGAAGTTCCAGGGCAGAGTCACGATTACCGCGGACGAATCCACGAGCACAGCCTACATGGAGCTGAGCAGCCTGAGATCTGAGGACACGGCCGTGTATTACTGTGCGAGAGA                       ATTACTACTACTACTACGGTATGGACGTCTGGGGCCAAGGGACCACGGTCACCGTCTCCTCAG





>ICKG9DXL
                                                                     ACCTCTGGATTCACCTTCAGCAGTTATGAAATGAACTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGATTTCATACATTAGTAATAGGGGAAGTACCATATTCTACGCAGACTCTGTGAAGGGCCGATTCACCATCTCCAGAGACAACGCCAAGAGCTTACTGTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCTGTTTATTATTGTGCGAGAGGGGCTAGCAGTGGCTGGTACTACTTTGACTACTGGGGCCAGGGAACCCTG
GAGGTGCAGCTGGTGGAGTCTGGGGGAGGCTTGGTACAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGTAGCTATAGCATGAACTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTTTCATACATTAGTAGTAGTAGTAGTACCATATACTACGCAGACTCTGTGAAGGGCCGATTCACCATCTCCAGAGACAATGCCAAGAACTCACTGTATCTGCAAATGAACAGCCTGAGAGACGAGGACACGGCTGTGTATTACTGTGCGAGAGA                 ACTACTTTGACTACTGGGGCCAGGGAACCCTGGTCACCGTCTCCTCAG
                                                                                                                                                                                                                                                                                                                         ACTACTTTGACTACTGGGGCCAGGGAACCCTGGTCACCGTCTCCTCAG




QT1MEPYF
                                                                                                                                             CTGGAGTGGGTGACATATGATGGAACTAATAAATATTACGCAGACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAGTTCCAAGAACACGGTGTATTTGCAAATGAACAGTCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAGAGGTGATGGCTTGGAGTATTACTTTGGTTCGGGGACCGGGAGGAACGGTATGGACGTCTGGGGCCAAGGGACCACG
CAGGTGCAGCTGGTGGAGTCTGGGGGAGGCGTGGTCCAGCCTGGGAGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGTAGCTATGGCATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCAGTTATATCATATGATGGAAGTAATAAATACTATGCAGACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAAAGA
ATTACTACTACTACTACGGTATGGACGTCTGGGGCCAAGGGACCACGGTCACCGTCTCCTCAG



caggtccagctggtgcagtcttgggct...gaggtgaggaagtctggggcctcagtgaaagtctcctgtagtttttctgggtttaccatc............accagctacggtatacattgggtgcaacagtcccctggacaagggcttgagtggatgggatggatcaaccctggc......aatggtagcccaagctatgccaagaagtttcag...ggcagattcaccatgaccagggacatgtccacaaccacagcctacacagacctgagcagcctgacatctgaggacatggctgtgtattactatgcaaga
                                     GGAAGTCTGGGGCCTCAGTGAAAGTCTCCTGTAGTTTTTCTGGGTTTACCATC............ACCAGCTACGGTATACATTGGGTGCAACAGTCCCCTGGACAAGGGCTTGAGTGGATGGGATGGATCAACCCTGGC......AATGGTAGCCCAAGCTATGCCAAGAAGTTTCAG...GGCAGATTCACCATGACCAGGGACATGTCCACAACCACAGCCTACACAGACCTGAGCAGCCTGACATCTGAGGACATGGCTGTGTATTACTATGCAAGA

>> 


%%





>10 HM855760|IGHV1-c*01|Ho IGHV1-c
CAGGTCCAGCTGGTGCAGTCTTGGGCT...GAGGTGAGGAAGTCTGGGGCCTCAGTGAAAGTCTCCTGTAGTTTTTCTGGGTTTACCATCACCAGCTACGGTATACATTGGGTGCAACAGTCCCCTGGACAAGGGCTTGAGTGGATGGGATGGATCAACCCTGGCAATGGTAGCCCAAGCTATGCCAAGAAGTTTCAGGGCAGATTCACCATGACCAGGGACATGTCCACAACCACAGCCTACACAGACCTGAGCAGCCTGACATCTGAGGACATGGCTGTGTATTACTATGCAAGA
                                     GGAAGTCTGGGGCCTCAGTGAAAGTCTCCTGTAGTTTTTCTGGGTTTACCATCACCAGCTACGGTATACATTGGGTGCAACAGTCCCCTGGACAAGGGCTTGAGTGGATGGGATGGATCAACCCTGGCAATGGTAGCCCAAGCTATGCCAAGAAGTTTCAGGGCAGATTCACCATGACCAGGGACATGTCCACAACCACAGCCTACACAGACCTGAGCAGCCTGACATCTGAGGACATGGCTGTGTATTACTATGCAAGA

>13 X62111|IGHV2-5*01|Homo IGHV2-5    diff = 1

>23 X92283|IGHV3-30-3*01|H IGHV3-30-3
CAGGTGCAGCTGGTGGAGTCTGGGGGAGGCGTGGTCCAGCCTGGGAGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGTAGCTATGCTATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCAGTTATATCATATGATGGAAGCAATAAATACTACGCAGACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAGA
CAGGTGCAGCTGGTGGAGTCTGGGGGAGGCGTGGTCCAGCCTGGGAGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGTAGCTATGCTATGCACTGGGTCCGCCAGGCTCCAGGCAAGGGGCTGGAGTGGGTGGCAGTTATATCATATGATGGAAGCAATAAATACTACGCAGACTCCGTGAAGGGCCGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTGCAAATGAACAGCCTGAGAGCTGAGGACACGGCTGTGTATTACTGTGCGAGAGA

>27 AB019438|IGHV3-47*02|H IGHV3-47
GAGGATCAGCTGGTGGAGTCTGGGGGAGGCTTGGTACAGCCTGGGGGGTCCCTGAGACCCTCCTGTGCAGCCTCTGGATTCGCCTTCAGTAGCTATGTTCTGCACTGGGTTCGCCGGGCTCCAGGGAAGGGTCCGGAGTGGGTATCAGCTATTGGTACTGGTGGTGATACATACTATGCAGACTCCGTGATGGGCCGATTCACCATCTCCAGAGACAACGCCAAGAAGTCCTTGTATCTTCAAATGAACAGCCTGATAGCTGAGGACATGGCTGTGTATTATTGTGCAAGAGA
GAGGATCAGCTGGTGGAGTCTGGGGGAGGCTTGGTACAGCCTGGGGGGTCCCTGAGACCCTCCTGTGCAGCCTCTGGATTCGCCTTCAGTAGCTATGTTCTGCACTGGGTTCGCCGGGCTCCAGGGAAGGGTCCGGAGTGGGTATCAGCTATTGGTACTGGTGGTGATACATACTATGCAGACTCCGTGATGGGCCGATTCACCATCTCCAGAGACAACGCCAAGAAGTCCTTGTATCTTCAAATGAACAGCCTGATAGCTGAGGACATGGCTGTGTATTATTGTGCAAGA

>30 M99678|IGHV3-52*01|Hom IGHV3-52
GAGGTGCAGCTGGTGGAGTCTGGGTGAGGCTTGGTACAGCCTGGAGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGTAGCTCCTGGATGCACTGGGTCTGCCAGGCTCCGGAGAAGGGGCTGGAGTGGGTGGCCGACATAAAGTGTGACGGAAGTGAGAAATACTATGTAGACTCTGTGAAGGGCCGATTGACCATCTCCAGAGACAATGCCAAGAACTCCCTCTATCTGCAAGTGAACAGCCTGAGAGCTGAGGACATGACCGTGTATTACTGTGTGAGAGG
GAGGTGCAGCTGGTGGAGTCTGGGTGAGGCTTGGTACAGCCTGGAGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGTAGCTCCTGGATGCACTGGGTCTGCCAGGCTCCGGAGAAGGGGCTGGAGTGGGTGGCCGACATAAAGTGTGACGGAAGTGAGAAATACTATGTAGACTCTGTGAAGGGCCGATTGACCATCTCCAGAGACAATGCCAAGAACTCCCTCTATCTGCAAGTGAACAGCCTGAGAGCTGAGGACATGACCGTGTATTACTGTGTGAGA

>32 M77301|IGHV3-64*05|Hom IGHV3-64  diff = 2

>35 AB019437|IGHV3-71*01|H IGHV3-71
GAGGTGCAGCTGGTGGAGTCCGGGGGAGGCTTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGTGACTACTACATGAGCTGGGTCCGCCAGGCTCCCGGGAAGGGGCTGGAGTGGGTAGGTTTCATTAGAAACAAAGCTAATGGTGGGACAACAGAATAGACCACGTCTGTGAAAGGCAGATTCACAATCTCAAGAGATGATTCCAAAAGCATCACCTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCCGTGTATTACTGTGCGAGAGA
GAGGTGCAGCTGGTGGAGTCCGGGGGAGGCTTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCTTCAGTGACTACTACATGAGCTGGGTCCGCCAGGCTCCCGGGAAGGGGCTGGAGTGGGTAGGTTTCATTAGAAACAAAGCTAATGGTGGGACAACAGAATAGACCACGTCTGTGAAAGGCAGATTCACAATCTCAAGAGATGATTCCAAAAGCATCACCTATCTGCAAATGAACAGCCTGAGAGCCGAGGACACGGCCGTGTATTACTGTGCGAGA

>49 M99685|IGHV4-55*01|Hom IGHV4-55
CAGGTGCAGCTGCAGGAGTCGGGCCCAGGACTGGTGAAGCCTTCGGAGACCCTGTCCCTCATCTGCGCTGTCTCTGGTGACTCCATCAGCAGTGGTAACTGGTGAATCTGGGTCCGCCAGCCCCCAGGGAAGGGGCTGGAGTGGATTGGGGAAATCCATCATAGTGGGAGCACCTACTACAACCCGTCCCTCAAGAGTCGAATCACCATGTCCGTAGACACGTCCAAGAACCAGTTCTACCTGAAGCTGAGCTCTGTGACCGCCGCGGACACGGCCGTGTATTACTGTGCGAGATA
CAGGTGCAGCTGCAGGAGTCGGGCCCAGGACTGGTGAAGCCTTCGGAGACCCTGTCCCTCATCTGCGCTGTCTCTGGTGACTCCATCAGCAGTGGTAACTGGTGAATCTGGGTCCGCCAGCCCCCAGGGAAGGGGCTGGAGTGGATTGGGGAAATCCATCATAGTGGGAGCACCTACTACAACCCGTCCCTCAAGAGTCGAATCACCATGTCCGTAGACACGTCCAAGAACCAGTTCTACCTGAAGCTGAGCTCTGTGACCGCCGCGGACACGGCCGTGTATTACTGTGCGAGA

>57 AB019437|IGHV7-81*01|H IGHV7-81
CAGGTGCAGCTGGTGCAGTCTGGCCATGAGGTGAAGCAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGTTACAGTTTCACCACCTATGGTATGAATTGGGTGCCACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGATGGTTCAACACCTACACTGGGAACCCAACATATGCCCAGGGCTTCACAGGACGGTTTGTCTTCTCCATGGACACCTCTGCCAGCACAGCATACCTGCAGATCAGCAGCCTAAAGGCTGAGGACATGGCCATGTATTACTGTGCGAGATA
CAGGTGCAGCTGGTGCAGTCTGGCCATGAGGTGAAGCAGCCTGGGGCCTCAGTGAAGGTCTCCTGCAAGGCTTCTGGTTACAGTTTCACCACCTATGGTATGAATTGGGTGCCACAGGCCCCTGGACAAGGGCTTGAGTGGATGGGATGGTTCAACACCTACACTGGGAACCCAACATATGCCCAGGGCTTCACAGGACGGTTTGTCTTCTCCATGGACACCTCTGCCAGCACAGCATACCTGCAGATCAGCAGCCTAAAGGCTGAGGACATGGCCATGTATTACTGTGCGAGAT
                          

 
                                                                                                                                    CTTGAGTGGATGGGATGGCTCAACGCTGGCAATGGTAACACAAGATATTCACAGAACTTCCAGGACAGAGTCACCATTACCAGGGACACATCCGCGACCACAGCCTACATGGAGCTGAGCAGCCTGAGATTTGAAGACACGGCTGTGTATTACTGTGCGAGAGATTTTGCCCCTATAGAGAAGGTCGTTCGGACTGGTTCGACCCCTGGGGCCGAGGGAACGCTG
CAGGTCCAGCTTGTGCAGTCTGGGGCTGAGGTGAAGAAGCCTGGGGCCTCAGTGAAGGTTTCCTGCAAGGCTTCTGGATACACCTTCACTAGCTATGCTATGCATTGGGTGCGCCAGGCCCCCGGACAAAGGCTTGAGTGGATGGGATGGATCAACGCTGGCAATGGTAACACAAAATATTCACAGAAGTTCCAGGGCAGAGTCACCATTACCAGGGACACATCCGCGAGCACAGCCTACATGGAGCTGAGCAGCCTGAGATCTGAAGACACGGCTGTGTATTACTGTGCGAGAGA                         ACAACTGGTTCGACCCCTGGGG CCAGGGAACCCTGGTCACCGTCTCCTCAG


9D26WT9E
>> data.reads{junk(k)}
                                                                                                                                    CTGGAATGGGTCTCAGTTCTTTATAGTGGTGGTAATACATACTACGCAGACTCCGTGAAGGGCAGATTCACCATCTCCAGAGACAATTCCAAGAACACGGTGTATCTTCAAATGCACAGCCTGAGCGCCGAGGACACGGCTGTGTATTACTGTGCGAGAAGGGCCCCGAAGAATGTAGTGGTGCCAGCTGCTACAAACTACTACTACTACTRTGGACGTCTGGGGCAAAGGGACCACG
GAGGTGCAGCTGGTGGAGTCTGGGGGAGGCTTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCGTCAGTAGCAACTACATGAGCTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTCTCAGTTATTTATAGCGGTGGTAGCACATACTACGCAGACTCCGTGAAGGGCAGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTTCAAATGAACAGCCTGAGAGCCGAGGACACGGCTGTGTATTACTGTGCGAGAGA                             ATTACTACTACTACTACGGTAT GGACGTCTGGGGCCAAGGGACCACGGTCACCGTCTCCTCAG



CTGGAATGGGTCTCAGTTCTTTATAGTGGTGGTAATACATACTACGCAGACTCCGTGAAGGGCAGATTCACCATCTCCAGAGACAATTCCAAGAACACGGTGTATCTTCAAATGCACAGCCTGAGCGCCGAGGACACGGCTGTGTATTACTGTGCGAGAAGGGCCCCGAAGAATGTAGTGGTGCCAGCTGCTACAAACTACTACTACTACTTGGACGTCTGGGGCAAAGGGACCACG
GAGGTGCAGCTGGTGGAGTCTGGGGGAGGCTTGGTCCAGCCTGGGGGGTCCCTGAGACTCTCCTGTGCAGCCTCTGGATTCACCGTCAGTAGCAACTACATGAGCTGGGTCCGCCAGGCTCCAGGGAAGGGGCTGGAGTGGGTCTCAGTTATTTATAGCGGTGGTAGCACATACTACGCAGACTCCGTGAAGGGCAGATTCACCATCTCCAGAGACAATTCCAAGAACACGCTGTATCTTCAAATGAACAGCCTGAGAGCCGAGGACACGGCTGTGTATTACTGTGCGAGAGA                             ATTACTACTACTACTACGGTATGGACGTCTGGGGCCAAGGGACCACGGTCACCGTCTCCTCAG

>> data.trimmed_VJ(junk(k),:)

ans =

   132    16   238

>> rep.V(data.ihmmune_collapsed(junk(k),1)).Sequence

ans =


>> rep.J(data.ihmmune_collapsed(junk(k),3)).Sequence

ans =




                                  
                                  
                                  
                                  
                                  
                                  
                                  
                                  
                                  
                                  
                                  